networks:
  rgb_network:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    restart: always
    container_name: rgb_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www/html:cached # Mount the local project directory
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - rgb_network

  app:
    build:
      context: .
    container_name: rgb_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached # Mount the local project directory
    ports:
      - 9000:9000
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: sqlsrv
      DB_HOST: 172.16.66.60
      DB_PORT: 1433
      DB_DATABASE: RGB_Bottle_Collect
      DB_USERNAME: sa
      DB_PASSWORD: sa@123QWEasz
      DB_TRUST_CERTIFICATE: true
    networks:
      - rgb_network

volumes:
  laravel_app_data:
